# Generated by Django 2.0.2 on 2018-03-20 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('production_house', models.CharField(max_length=100)),
                ('production_house_add', models.CharField(max_length=300)),
                ('local_agent', models.CharField(blank=True, default='', max_length=100)),
                ('local_agent_add', models.CharField(blank=True, default='', max_length=300)),
                ('passport_no', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Passport is not valid', regex='^\\+?1?\\d{6,9}$')])),
                ('passport_validity', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('cinematographer', models.CharField(max_length=100)),
                ('art_director', models.CharField(max_length=100)),
                ('script', models.FileField(upload_to='scripts/')),
                ('shoot_timing', models.TimeField()),
                ('shoot_start', models.DateField()),
                ('shoot_end', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_places.Producer')),
            ],
        ),
    ]
