# Generated by Django 2.0.2 on 2018-03-22 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='contact',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='production',
            name='local_line_producer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='production',
            name='local_line_producer_add',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='production',
            name='production_house',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='production',
            name='production_house_add',
            field=models.CharField(default='', max_length=300),
        ),
    ]
