# Generated by Django 2.0.2 on 2018-03-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_places', '0002_auto_20180322_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
