# Generated by Django 2.0.2 on 2018-03-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_places', '0003_producer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='shoot_end',
            new_name='shoot_end_date',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='shoot_start',
            new_name='shoot_start_date',
        ),
        migrations.AlterField(
            model_name='production',
            name='producer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
