# Generated by Django 2.0.2 on 2018-03-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_places', '0004_auto_20180323_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='local_line_producer_add',
            new_name='local_line_producer_address',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='production_house_add',
            new_name='production_house_address',
        ),
        migrations.AddField(
            model_name='production',
            name='undertaking',
            field=models.FileField(default='', upload_to='undertaking/'),
        ),
    ]
